
name: CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners 
      - name: Build image login and push to container registry
        run: |
          docker build -t ${{ secrets.REGISTRY_USERNAME }}/mario-app:v1.0 .
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          docker push ${{ secrets.REGISTRY_USERNAME }}/mario-app:v1.0

